default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hugomorais
  password: 
  timeout: 5000

development:
  <<: *default
  database: hmRoR
test:
  <<: *default
  database: hmRoR

production:
  <<: *default
  database: hmRoR